grafana-cloud:
  cluster:
    name: kind-local
  clusterMetrics:
    enabled: true
  clusterEvents:
    enabled: true
  alloy-metrics:
    enabled: true
  alloy-singleton:
    enabled: true
  podLogs:
    enabled: true
