apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goldilocks
  namespace: argocd
spec:
  destination:
    namespace: goldilocks
    server: https://kubernetes.default.svc
  project: platform
  source:
    helm:
      valueFiles:
        - values-kind-local.yaml
        - values.yaml
    path: ./workloads/goldilocks
    repoURL: git@github.com:wvides/argo-experimental.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
