apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-cloud
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: infra
  source:
    helm:
      valueFiles:
        - values.yaml
    path: ./workloads/grafana-cloud
    repoURL: https://github.com/wvides/argo-experimental.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
